# Generated by Django 2.0.7 on 2018-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.TextField(verbose_name='время принятия запроса')),
                ('method_in', models.TextField(verbose_name='использованный метод')),
                ('host_in', models.TextField(verbose_name='название хоста')),
                ('json_in', models.TextField(verbose_name='json-содержимое')),
            ],
            options={
                'verbose_name_plural': 'запросы',
                'verbose_name': 'запрос',
            },
        ),
    ]
