# Generated by Django 2.0.7 on 2018-07-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receive',
            options={'verbose_name': 'полученный запрос', 'verbose_name_plural': 'полученные запросы'},
        ),
    ]
