# Generated by Django 2.0.7 on 2018-07-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.TextField(verbose_name='URI')),
                ('json_out', models.TextField(verbose_name='отправленный json')),
                ('status', models.TextField(verbose_name='статус ответа')),
                ('json_in', models.TextField(verbose_name='ответный json')),
            ],
            options={
                'verbose_name_plural': 'отправленные запросы',
                'verbose_name': 'отправленный запрос',
            },
        ),
    ]
